apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: museum
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
      volumes:
        - name: mysql-initdb
          configMap:
              name: mysql-initdb-config
        - name: mysql-persistent-storage
          emptyDir: {}
