apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      containers:
        - name: php
          image: medanyyy/laravel-app:v1.2
          imagePullPolicy: Always
          volumeMounts:
            - name: app
              mountPath: /app
          command: ["php-fpm"]
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    cp -r /var/www/. /app
                    rm /app/public/storage
                    ln -s /app/storage/app/public /app/public/storage
                    chmod -R 777 /app/storage
                    chmod -R 777 /app/bootstrap/cache

      volumes:
        - name: app
          persistentVolumeClaim:
            claimName: app
