apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: php
    tier: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
