pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                script {
                    sh 'echo hello minikube'
                }
            }
        }
    }
}
